version: '3.8'
services:
  mysqldb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 3036:3036
    networks:
      - new
  nest:
    image: app/
    depends_on:
      - mysqldb
    ports:
      - 3000:3000
    networks:
      - new
networks:
  new:
