version: "3.8"

services:
  nest:
    build: .
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env
    links:
      - database

  database:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - ~/database/nest:/var/lib/mysql
